Make eDigitalOut and eDigitalIn remember direction and state of IO0-3 for U12
labjack/LabJackPython pull request #115
Opened 2021-08-19 17:27 UTC by fgrfl

On linux (__os_name != "nt"), when setting one of the IOs to Input or Output, all of them are changed, not only the channel you want to change:

If you call eDigitalIn(0), IO0, IO1, IO3 and IO4 are set to input.
If you call eDigitalOut(0, 1), IO0 is set as ouput and high, IO1 to IO3 are set to output and low.

For D0-D15, the current state is fetched from the U12 and the newly written state only differs in the channel given as parameter.

On windows, the C function EDigitalIn or EDigitalOut is called, which caches the current state locally.

Since the current direction of IO0-3 is not returned by the U12, the state needs to be cached locally like in the C implementation.

2021-08-19 22:11 UTC, sjarman28 requested changes
It does look like eDigitalIn had a bug and your eDigitalOut change looks good. However, your change will only work if you track the direction in every function that the direction can be set, so eDigitalIn, eDigitalOut, rawDIO, and rawSHT1X. Please change it so the direction is tracked everywhere.

2021-08-19 22:12 UTC, sjarman28 commented
Also note that rawSHT1X should set IO0 to input, IO1 to output, and IO2 and IO3 according to the input settings.

2021-08-20 08:36 UTC, fgrfl commented
I added tracking of the IO State changes to every raw function that potentially writes to the IOs: rawAISample, rawDIO, rawCounterPWMDIO, rawAIBurst, rawAIContinuous and rawSHT1X

2021-08-31 11:37 UTC, fgrfl commented
Is this change sufficient?

2021-08-31 15:41 UTC, sjarman28 approved these changes
Looks good, thanks

2021-08-31 15:41 UTC, merged

2021-10-21 19:35 UTC, sjarman28 commented
This pull request was mainly looking at the IO terminal tracking. The D-line issue you are seeing should be a pretty quick fix, and I will make a new branch and pull request for it here shortly.